# Project
version=12.1.0
group=com.mrbysco.armorposer

# Common
minecraft_version=1.21.9
neoform_version=1.21.9-20250930.151910
mixin_version=0.15.0+mixin.0.8.7
mixinextras_version=0.4.1

# NeoForge
neo_version=21.9.13-beta
parchment_minecraft_version=1.21.8
parchment_mapping_version=2025.09.14

# Fabric
fabric_version=0.134.0+1.21.9
fabric_loader_version=0.17.2
cloth_config_version=20.0.148
mod_menu_version=16.0.0-rc.1

# Mod options
mod_name=ArmorPoser
mod_author=Mrbysco
mod_id=armorposer

#Publishing
curseforge_id=450663
modrinth_id=PFwYNrHb

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false